fight_time: 15
fight_message: "§c§l%sec%초 후 전투가 종료됩니다"
fight_end_message: "§c§l전투가 종료되었습니다"
explosion_damage_percent: 30
blocked_commands_during_fight:
  - /team
  - /bed


xpbottle_diamond_rate: 10
netherrack_despawn_time: 1000
show_death_location: true
only_show_death_location_in_same_world: true

# normal | end | nether
elytra_disable_dimension:
  - end
# default: 1
elytra_damage_during_fight: 2
mace_cooldown_per_damage: 2
totem_drop_chance: 0.2