name: SimpleSMP
version: '1.0.0'
main: me.ujun.simplesmp.SimpleSMP
api-version: '1.21'
commands:
  bed:
    permission: simplesmp.cmd.bed
  xpbottle:
    permission: simplesmp.cmd.xpbottle
  randomspawn:
    permission: simplesmp.cmd.randomspawn
  simplesmp-reload:
    permission: op

permissions:
  simplesmp.cmd.bed:
    default: true
  simplesmp.cmd.xpbottle:
    default: true
  simplesmp.cmd.randomspawn:
    default: true